[package]
name = "mila"
version = "0.1.0"
edition = "2021"
description = "Mila Lang"
authors = ["Paulo Gabriel Justino Bezerra <pgjbzr@gmail.com>"]

[dependencies]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"